# Generated by Django 4.2.4 on 2023-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfund_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
