# Generated by Django 4.2.4 on 2023-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zfund_app', '0004_productcategory_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
